name: Bindist installation
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      tool:
        description: Tool
        required: true
        type: string
      version:
        description: Version
        required: true
        type: string
      metadataFile:
        description: Metadata file
        required: true
        default: ghcup-0.0.7.yaml
        type: string
      channel:
        description: Distribution channel (main|prerelease|nightly)
        required: true
        default: Main
        type: string
env:
  BOOTSTRAP_HASKELL_NONINTERACTIVE: 1
  BOOTSTRAP_HASKELL_MINIMAL: 1
  BOOTSTRAP_HASKELL_ADJUST_BASHRC: 1
  TOOL: ${{ github.event.inputs.tool }}
  VERSION: ${{ github.event.inputs.version }}
  METADATA_FILE: ${{ github.event.inputs.metadataFile }}
  CHANNEL: ${{ github.event.inputs.channel }}
jobs:
  bindist-install-mac-win:
    name: Build non-linux
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v3

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Install ghcup and bindist
        run: .github/workflows/install-bindist.sh

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Test2
        run: TOOL=test .github/workflows/test-bindist.sh

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Test bindist
        run: .github/workflows/test-bindist.sh

